name: Manual Publish SDK

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. 1.0.0)'
        required: true

jobs:
  publish:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Build for iOS Simulator
        run: |
          xcodebuild \
            -scheme SwiftEmbedSDK \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2' \
            -sdk iphonesimulator \
            clean build

      - name: Create Git Tag
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
